/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import control.fornecedorController;
import java.util.ArrayList;
import java.util.Optional;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.fornecedor;
import model.fornecedorSQL;
import org.mindrot.jbcrypt.BCrypt;

/**
 *
 * @author Pedro
 */
public class fornecedorGUI extends javax.swing.JFrame {

    private fornecedorController fornecedorController;

    /**
     * Creates new form usuarioGUI
     */
    public fornecedorGUI(fornecedorController fornecedorController) {
        this.fornecedorController = fornecedorController;
        initComponents();
        popularTabela(fornecedorController.getAll());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblRs = new javax.swing.JLabel();
        txtNf = new javax.swing.JTextField();
        lblNf = new javax.swing.JLabel();
        txtRs = new javax.swing.JTextField();
        lblCnpj = new javax.swing.JLabel();
        btnBuscarId = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFornecedores = new javax.swing.JTable();
        btnBuscarRs = new javax.swing.JButton();
        txtCnpj = new javax.swing.JTextField();
        btnBuscarCnpj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblId.setLabelFor(txtId);
        lblId.setText("ID:");

        lblRs.setLabelFor(txtRs);
        lblRs.setText("Razao Social:");

        lblNf.setLabelFor(txtNf);
        lblNf.setText("Nome Fantasia:");

        lblCnpj.setLabelFor(txtCnpj);
        lblCnpj.setText("CNPJ:");

        btnBuscarId.setText("Buscar");
        btnBuscarId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarIdActionPerformed(evt);
            }
        });

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        tblFornecedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblFornecedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFornecedoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblFornecedores);

        btnBuscarRs.setText("Buscar");
        btnBuscarRs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarRsActionPerformed(evt);
            }
        });

        btnBuscarCnpj.setText("Buscar");
        btnBuscarCnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCnpjActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtId)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnBuscarId))
                                    .addComponent(lblId)
                                    .addComponent(lblNf)
                                    .addComponent(txtNf, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCnpj)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtRs, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnBuscarRs))
                                    .addComponent(lblRs)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnBuscarCnpj))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnNovo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSalvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAlterar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnExcluir)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblId)
                            .addComponent(lblRs))
                        .addGap(46, 46, 46)
                        .addComponent(lblNf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarCnpj)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarId)
                            .addComponent(btnBuscarRs)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblCnpj)
                        .addGap(28, 28, 28)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnSalvar)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarIdActionPerformed
        int id = Integer.valueOf(txtId.getText());
        Optional<fornecedor> f = fornecedorController.getById(id);
        f.ifPresentOrElse(fs -> {
            txtNf.setText(fs.getRs());
            txtRs.setText(fs.getNf());
            txtCnpj.setText(String.valueOf(fs.getCnpj()));
        }, () -> {
            JOptionPane.showMessageDialog(this, "ID nao encontrado!");
            txtId.setText("");
            txtId.requestFocus();
        });
    }//GEN-LAST:event_btnBuscarIdActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        txtId.setText("");
        txtNf.setText("");
        txtRs.setText("");
        txtCnpj.setText("");
        txtId.requestFocus();
        popularTabela(fornecedorController.getAll());
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        String rS = txtRs.getText();
        String nF = txtNf.getText();
        int cnpj = Integer.valueOf(txtCnpj.getText());

        fornecedorController.add(rS, nF, cnpj);

        JOptionPane.showMessageDialog(this, "Fornecedor Salvo!");
        popularTabela(fornecedorController.getAll());
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int res = JOptionPane.showConfirmDialog(
                this,
                "Tem certeza?",
                "Confirmar exclusao",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
        );
        if (res == JOptionPane.YES_OPTION) {
            int id = Integer.valueOf(txtId.getText());
            if (fornecedorController.delete(id)) {
                JOptionPane.showMessageDialog(this, "Fornecedor excluido!");
            } else {
                JOptionPane.showMessageDialog(this, "Fornecedor nao encontrado!");
            }
            popularTabela(fornecedorController.getAll());

        } else {
            JOptionPane.showMessageDialog(this, "Abre o olho japones!");
        }
        popularTabela(fornecedorController.getAll());
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        int id = Integer.valueOf(txtId.getText());
        String rS = txtNf.getText();
        String nF = txtRs.getText();
        int cnpj = Integer.valueOf(txtCnpj.getText());

        if (fornecedorController.update(id, rS, nF, cnpj)) {
            JOptionPane.showMessageDialog(this, "Fornecedor alterado!");
        } else {
            JOptionPane.showMessageDialog(this, "Fornecedor nao encontrado!");
        }
        popularTabela(fornecedorController.getAll());
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void tblFornecedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFornecedoresMouseClicked
        int id = (int) tblFornecedores.getValueAt(tblFornecedores.getSelectedRow(), 0);
        Optional<fornecedor> f = fornecedorController.getById(id);
        f.ifPresentOrElse(fs -> {
            txtId.setText(String.valueOf(fs.getId()));
            txtNf.setText(fs.getRs());
            txtRs.setText(fs.getNf());
            txtCnpj.setText(String.valueOf(fs.getCnpj()));
        }, () -> {
            JOptionPane.showMessageDialog(this, "ID nao encontrado!");
            txtId.setText("");
            txtId.requestFocus();
        });
    }//GEN-LAST:event_tblFornecedoresMouseClicked

    private void btnBuscarRsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarRsActionPerformed
        String rS = txtRs.getText();
        Optional<fornecedor> f = fornecedorController.getByRs(rS);
        f.ifPresentOrElse(fs -> {
            txtRs.setText(fs.getRs());
            txtNf.setText(fs.getNf());
            txtCnpj.setText(String.valueOf(fs.getCnpj()));
        }, () -> {
            JOptionPane.showMessageDialog(this, "Razao Social nao encontrada!");
            txtRs.setText("");
            txtRs.requestFocus();
        });
    }//GEN-LAST:event_btnBuscarRsActionPerformed

    private void btnBuscarCnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCnpjActionPerformed
        int cnpj = Integer.valueOf(txtCnpj.getText());
        Optional<fornecedor> f = fornecedorController.getByCnpj(cnpj);
        f.ifPresentOrElse(fs -> {
            txtRs.setText(fs.getNf());
            txtNf.setText(fs.getRs());
            txtCnpj.setText(String.valueOf(fs.getCnpj()));
        }, () -> {
            JOptionPane.showMessageDialog(this, "CNPJ nao encontrado!");
            txtCnpj.setText("");
            txtCnpj.requestFocus();
        });
    }//GEN-LAST:event_btnBuscarCnpjActionPerformed

    public void popularTabela(ArrayList<fornecedor> fornecedores) {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Razao Social");
        model.addColumn("Nome Fantasia");
        model.addColumn("CNPJ");

        for (fornecedor u : fornecedores) {
            model.addRow(new Object[]{u.getId(), u.getRs(), u.getNf(), u.getCnpj()});
        }
        tblFornecedores.setModel(model);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fornecedorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fornecedorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fornecedorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fornecedorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                fornecedorSQL fornecedorSQL = new fornecedorSQL();
                fornecedorController usuarioController = new fornecedorController(fornecedorSQL);
                new fornecedorGUI(usuarioController).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnBuscarCnpj;
    private javax.swing.JButton btnBuscarId;
    private javax.swing.JButton btnBuscarRs;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCnpj;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNf;
    private javax.swing.JLabel lblRs;
    private javax.swing.JTable tblFornecedores;
    private javax.swing.JTextField txtCnpj;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNf;
    private javax.swing.JTextField txtRs;
    // End of variables declaration//GEN-END:variables
}
